### ISSUE TITLE
Content Packs upload json  error

### ISSUE THREAD

**Issue by oliver-yu** [orthonovum/Graylog_PAN_Dashboards#2]
![image](https://user-images.githubusercontent.com/18164716/180602663-3e8454b9-7c4e-477e-b62a-ad481a676c4b.png)

Hi guru!
 I downloaded the json file with  Graylog4.33 "Content Packs" upload "PANOS_Dashboards_Graylog_content-pack.json" error, please help to see, what is the reason,  and im  Palo Alto OS version 9.01 .
Thank you!

**Comment by oliver-yu** [comment]
![image](https://user-images.githubusercontent.com/18164716/180602591-364dba73-31d4-46ff-a7e7-e5891cf427d7.png)

**Comment by orthonovum** [comment]
Removed the extra )" character from that line

**Comment by oliver-yu** [comment]
![image](https://user-images.githubusercontent.com/18164716/180610761-34407a0e-6c8d-41ab-baa0-34377b5c1f50.png)
![image](https://user-images.githubusercontent.com/18164716/180610803-ec6da734-a945-49b8-b9b8-cf0fe0a7687a.png)
![image](https://user-images.githubusercontent.com/18164716/180610835-2ab328b5-9a38-4941-ae12-2bd5c67bf37f.png)



I'm Removed the  ")"  ，json file upload  succeeded. but new problems arise during install ,please help look at it, thank you!
